### ISSUE TITLE
algo is bugged when alignement nb is not 5

### ISSUE THREAD

**Issue by lojesu** [glegendr/gomoku#1]
- when alignement nb is not 5 algo's first move is all the time ```0 0```
- when human win in any case algo is "mongolised" he play in ```0 0``` but the case is not empty so infinite loop

and sorry but my issue is cool 👯

**Comment by glegendr** [comment]
Thank's for the Issue ! @lojesu is hadly working on this issue right now, it will be fix as soon as possible

**Comment by lojesu** [comment]
i adjust my issue, algo play on the first case he find if alignement nb is less or equal than 3 i don't know why yet but i continue my research
